"""Final report agent entrypoint and orchestration."""

import json

from nodes.tasks import get_agent_definition, get_task_definition
from tools import report_packet as report_packet_tools
from tools import report_pdf as report_pdf_tools
from tools.report_normalization import normalize_final_report
from tools.report_packet import ARABIC_PDF_SYSTEM_PROMPT, REPORT_SYSTEM_PROMPT
from tools.crewai_agent_tools import run_crewai_json_agent


GEMINI_REPORT_MODEL = "gemini-2.5-flash"


def call_report_agent(report_packet, *, api_key, model_name=GEMINI_REPORT_MODEL, timeout=60):
    """Run the CrewAI final report agent and parse the structured JSON report."""
    agent_def = get_agent_definition("report")
    task_def = get_task_definition("report")
    return run_crewai_json_agent(
        role=agent_def["role"],
        goal=agent_def["goal"],
        backstory=agent_def["backstory"],
        task_prompt=(
            f"{task_def['description']}\n\n"
            f"{json.dumps(report_packet, ensure_ascii=False, indent=2)}"
        ),
        expected_output=task_def["expected_output"],
        api_key=api_key,
        model_name=model_name,
        max_tokens=8192,
        timeout=timeout,
        label="CrewAI report agent",
    )


def build_report_packet(pipeline_result):
    """Build the structured packet consumed by the report agent."""
    return report_packet_tools.build_report_packet(pipeline_result)


def build_fallback_report(pipeline_result, error=None):
    """Build a structured report when the CrewAI report agent is unavailable."""
    return report_packet_tools.build_fallback_report(pipeline_result, error=error)


def call_arabic_pdf_report(report, *, api_key, model_name=GEMINI_REPORT_MODEL, timeout=60):
    """Run the CrewAI Arabic PDF translator and parse the structured Arabic report."""
    return report_packet_tools.call_arabic_pdf_report(
        report,
        api_key=api_key,
        model_name=model_name,
        timeout=timeout,
    )


def build_fallback_arabic_pdf_report(report, error=None):
    """Build an Arabic-labeled PDF report if translation is unavailable."""
    return report_packet_tools.build_fallback_arabic_pdf_report(report, error=error)


def build_arabic_pdf_report(report, *, api_key, model_name=GEMINI_REPORT_MODEL):
    """Return an Arabic report object for PDF generation only."""
    return report_packet_tools.build_arabic_pdf_report(report, api_key=api_key, model_name=model_name)


def save_report_pdf(report, *, upload_dir, submission_id=None, patient_name=None, code_no=None, arabic=False):
    """Save the structured report as a PDF under uploads/reports and return metadata."""
    return report_pdf_tools.save_report_pdf(
        report,
        upload_dir=upload_dir,
        submission_id=submission_id,
        patient_name=patient_name,
        code_no=code_no,
        arabic=arabic,
    )


def run_report_agent(pipeline_result, *, api_key, model_name=GEMINI_REPORT_MODEL):
    """Return a structured final report generated by the CrewAI report agent."""
    report_packet = build_report_packet(pipeline_result)
    try:
        report = call_report_agent(
            report_packet,
            api_key=api_key,
            model_name=model_name,
        )
        llm_error = None
    except RuntimeError as exc:
        report = build_fallback_report(pipeline_result, error=str(exc))
        llm_error = str(exc)
    else:
        report = normalize_final_report(report)

    return {
        "engine": "crewai",
        "model": model_name,
        "report_packet": report_packet,
        "report": normalize_final_report(report),
        "error": llm_error,
    }
